### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by infinityyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy** [natrixdev/Discord-Server-Boost#1]
File "C:\Users\User\Downloads\Discord-Server-Boost-main\Discord-Server-Boost-main\ServerBooster.py", line 13
    try modules;
    ^
SyntaxError: invalid syntax

**Comment by ledges** [comment]
> File "C:\Users\User\Downloads\Discord-Server-Boost-main\Discord-Server-Boost-main\ServerBooster.py", line 13 try modules; ^ SyntaxError: invalid syntax
 
Sorry to tell you but this is fake, this guy doesn't even know whats hes actually doing hes just putting random modules and random syntax and throwing them on github pretending they're real.
